apiVersion: v1
kind: Secret
metadata:
  name: mydockerhubsecret-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "a2hhbGVkbmVqaTI1QGdtYWlsLmNvbQ==:Y29kZWJ1aWxkMjU="
        }
      }
    }

