apiVersion: v1
kind: Secret
metadata:
  name: mydockerhubsecret-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "Z2l0aHViX3BhdF8xMUJJVkpQWlkwTzlDS25jeUtRcGFMX0ZKYXlnMnk3dVRQWkpQRTdQV2JZdjZN
U1VoSWlOMnVNc1FRa1NDdzl4S282QTZSV0NKQUpYcHRXV0hD"
        }
      }
    }

