apiVersion: v1
kind: Secret
metadata:
  name: mydockerhubsecret-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "a2hhbGVkbmVqaTI1QGdtYWlsLmNvbQ==",
          "password": "Y29kZWJ1aWxkMjU=",
          "email": "khaledneji25@gmail.com",
          "auth": "a2hhbGVkbmVqaTI1QGdtYWlsLmNvbTpjb2RlYnVpbGQyNQ=="
        }
      }
    }
