apiVersion: v1
kind: Secret
metadata:
  name: mydockerhubsecret-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}

